NDefines.NPop.MIN_HABITABILITY_TO_MIGRATE = 0.2
NDefines.NAI.POP_FOOD_MIN = 4
NDefines.NAI.COLONIZE_HABITABILITY_MIN = 0.2
NDefines.NGameplay.SECTOR_REVOKE_SYSTEM_COST = 5
NDefines.NGameplay.CORE_SECTOR_SYSTEM_CAP = 8